### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ndelangen** [jbovenschen/storybook-addon-a11y#5]
I'm not sure if this package is still maintained, Do you need help?

I'm happy to integrate this into the storybook monorepo if you'd like?

There's a 3.0.0 release coming, and I'd like to make sure addons are maintained, we're willing to help where we can!

Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by jbovenschen** [comment]
I currently don't actively maintain this addon, currently focused on other projects.

It's maybe a good idea to move it to the storybook repo so other people can collaborate on it.

Happy to hear from you.

**Comment by ndelangen** [comment]
If you'd like us to maintain this, we can. 

**Can you:**
- [ ]  transfer the ownsership of the repo to the [storybooks organisation](https://github.com/storybooks).
- [ ] add [ndelangen](https://www.npmjs.com/~ndelangen) as admin / collaborator.

Thank you / bedankt !

**Comment by jbovenschen** [comment]
I get an error while trying to transfer the repo to the storybooks organization.

'You don’t have the permission to create repositories on storybooks'

Never did this before so any help will be appreciated. 

I added you as an admin to the npm pacakge.

**Comment by ndelangen** [comment]
Can you make me an admin for this repo? I'll move it over, I never moved a repo either 😃

**Comment by jbovenschen** [comment]
Done, happy to work again on it when I have more spare time to do so :)

**Comment by ndelangen** [comment]
I don't have enough rights to do it yet:
![screen shot 2017-05-16 at 13 23 31](https://cloud.githubusercontent.com/assets/3070389/26103675/e3ffcb84-3a3a-11e7-9046-5fbe8425b5c2.png)

I'm missing the `settings` tab.

**Comment by ndelangen** [comment]
Never mind I need to accept the invitation first

**Comment by ndelangen** [comment]
Nope still can't access `settings`, can you increase my privileges to admin?

**Comment by jbovenschen** [comment]
Do you know where that option is?

**Comment by ndelangen** [comment]
Yup, you need to make a team, assign a user to it and assign admin privileges to the group:
<img width="1014" alt="screen shot 2017-05-16 at 17 22 50" src="https://cloud.githubusercontent.com/assets/3070389/26113986/686aa3d2-3a5c-11e7-855f-fbfbd057dd3d.png">

**Comment by jbovenschen** [comment]
That's only doable when working with a Github organization, if you have a personal repo you can only add Collaborators.

**Comment by jbovenschen** [comment]
Maybe you can add me to the storybooks team for now, so I can migrate the project?

**Comment by ndelangen** [comment]
Can you maybe try migrating it to my personal user?
<img width="475" alt="screen shot 2017-05-18 at 23 55 09" src="https://cloud.githubusercontent.com/assets/3070389/26225033/81648e1e-3c25-11e7-8074-eeda33d98410.png">

**Comment by jbovenschen** [comment]
Done!

**Comment by jbovenschen** [comment]
@ndelangen Dit transfer the repo to your account, but see it didn't move yet? Still interested in this repo?

**Comment by ndelangen** [comment]
I am, I did not get any notification, I guess I'll have to contact github support.

Sorry this is taking so much of your time 🙃

**Comment by jbovenschen** [comment]
Thank you!

Did transfer the project to the `storybook-eol` organization.
